= Martyr Domain
:doctype: book
:icons: font
:revdate: May 1, 2025
:stylesdir: ../../../../css
// Custom attributes
ifndef::env-github[]
include::../../../../attributes.adoc[]
endif::[]

// tag::subclass[]

Followers of gods that believe in taking on the suffering of those around them.
Stalwart and unflinching, these intrepid souls seek to ease the suffering of those around them.
While typically altruistic, sometimes their motivations are further afield, belonging to strange cults of suffering or acceptance.

[#cleric-subclass-matryr-domain-spells]
== Domain Spells
You gain domain spells at the {class-name-cleric} levels listed on the <<cleric-domain-martry-spells-table,Martyr Domain Spells table>>.
Once you gain a domain spell, you always have it prepared, and it doesn't count against the number of spells you can prepare each day.
If you have a domain spell that doesn't appear on the {class-name-cleric} spell list, the spell is nonetheless a {class-name-cleric} spell for you.

[#cleric-domain-martry-spells-table]
.{subclass-name-cleric-martyr} Domain Spells (table)
[%header,cols="1,3"]
|===
| {class-name-cleric} Level | Spells

| 1st
| <<spell-cure-wounds>>, Shield of Faith

| 3rd
| Lesser Restoration, Warding Bond

| 5th
| Remove Curse, Revivify

| 7th
| Death Ward, Resilient Sphere

| 9th
| Greater Restoration, Mass Cure Wounds
|===

[#cleric-subclass-matryr-clad-in-grace]
== Clad in Grace
Starting at 1st level, while you are not wearing any armor, your Armor Class equals 10 + your Constitution modifier + your Wisdom modifier.
You can use a shield and still gain this benefit.

[#cleric-subclass-matryr-relieve-suffering]
== Relieve Suffering
Starting at 1st level, when you cast a spell of 1st level or higher that restores hit points, you can expend some of your own hit points to increase the amount another creature that is healed by the spell regains, expending a number of hit points up to your {class-name-cleric} level to increase the amount one creature is healed by an equivalent value.

Additionally, you can touch a creature suffering a disease or the blinded, deafened, paralyzed or poisoned condition and transfer that disease or condition to yourself.
Starting at 9th level, the range of conditions you can take increases, including exhaustion (1 level at a time), petrified, stunned, the effect of a curse, or any reduction to their ability scores.
You are afflicted by the effect in the same manner the creature you took it was, for the same duration and possible methods of ending the effect.

You can transfer a condition affecting another creature to yourself a number of times equal to your Wisdom modifier, regaining all uses on a long rest.

[#cleric-subclass-matryr-channel-divinity-bear-the-burden]
== Channel Divinity: Bear the Burden
Starting at 2nd level, you can use your <<cleric-feature-channel-divinity,Channel Divinity>> to bring all the suffering your allies suffer onto yourself.

As an action, you present your holy symbol and enter a divine trance.
Until the start of your next turn, your movement speed becomes zero and you gain temporary hit points equal to twice your {class-name-cleric} level.
Any time an allied creature within 30 feet of you takes damage, they have resistance to the damage taken, but you take damage equal to the damage they take.

[#cleric-subclass-matryr-overcome-adversity]
== Overcome Adversity
Starting at 6th level, when you use your <<cleric-subclass-matryr-relieve-suffering>> to take the condition affecting a creature, you can repeat the original saving throw against the feature if it had one.
On success, the condition ends instead of being transferred.

Additionally, when you take damage as a result of the Warding Bond spell, you have resistance to that damage.

[#cleric-subclass-matryr-divine-empowerment]
== Divine Empowerment
At 8th level, pick one of the following options:

[#cleric-subclass-matryr-divine-strike]
Divine Strike::
At 8th level, you gain the ability to infuse your weapon strikes with divine energy.
Once on each of your turns when you hit a creature with a weapon attack made as part of the attack action, you can cause the attack to deal an extra 1d8 radiant damage to the target.
+
When you reach 11th level, the extra damage increases to 2d8, and when you reach 17th level, the extra damage increases to 3d8.

[#cleric-subclass-matryr-potent-spellcasting]
Potent Spellcasting::
Starting at 8th level, you add your Wisdom modifier to the damage you deal with any {class-name-cleric} cantrip.

[#cleric-subclass-matryr-unyielding-concentration]
== Unyielding Concentration
Starting at 17th level, while you are concentrating on a {class-name-cleric} spell that targets you or your allies, your concentration can’t be broken as a result of taking damage.


// end::subclass[]

// tag::spell-descriptions[]

= Spells

[#spell-cure-wounds]
== Cure Wounds
include::../../../../04_Rules_of_Magic/Spell_Descriptions//Cure_Wounds.adoc[leveloffset=+2, tag=spell-description]

// end::spell-descriptions[]