= {subclass-name-cleric-sacred-mandate}
:doctype: book
:icons: font
:revdate: May 24, 2025
:stylesdir: ../../../../css
// Custom attributes
:class-name-cleric: Cleric
:subclass-name-cleric-sacred-mandate: Sacred Mandate
ifndef::env-github[]
include::../../../../attributes.adoc[]
endif::[]

// tag::subclass[]

[sidebar]
****
Your deity doesn’t assign you a job—they grant you a mandate.
****

You embody a divine imperative—an expression of your deity’s focus.
This Sacred Mandate grants you access to specific powers that you shape through your chosen domain.

At 1st level, you choose a **Mandate Domain**, such as Knowledge, Life, or War.
Your mandate grants you a collection of features as outlined below.

[#cleric-subclass-sacred-mandate-spells]
== Mandate Spells

You gain the spell list associated with your selected domain.
These spells count as {class-name-cleric} spells for you and are always prepared.

[#cleric-subclass-sacred-mandate-spells-table]
.The Mandate Spells (table)
[%header,cols="1,3,3,3,3,3"]
|===
| Domain | 1st Level | 3rd Level | 5th Level | 7th Level | 9th Level

| Knowledge
| Identify, Command
| Augury, Detect Thoughts
| Clairvoyance, Speak with Dead
| Arcane Eye, Divination
| Legend Lore, Scrying

| Life
| Cure Wounds, Bless
| Lesser Restoration, Spiritual Weapon
| Beacon of Hope, Revivify
| Death Ward, Guardian of Faith
| Mass Cure Wounds, Raise Dead

| Light
| Color Spray, Guiding Bolt
| Continual Flame, Moonbeam
| Daylight, Spirit Guardians
| Arcane Eye, Divination
| Dream, Scrying

| Storm
| Thunderwave, Fog Cloud
| Gust of Wind, Shatter
| Call Lightning, Wind Wall
| Control Water, Ice Storm
| Control Weather, Flame Strike

| Trickery
| Disguise Self, Charm Person
| Mirror Image, Pass Without Trace
| Bestow Curse, Major Image
| Greater Invisibility, Hallucinatory Terrain
| Mislead, Seeming

| War
| Divine Favor, Shield of Faith
| Magic Weapon, Spiritual Weapon
| Revivify, Slow
| Stoneskin, Freedom of Movement
| Hold Monster, Flame Strike
|===

== Mandate Proficiency
When you choose this domain at 1st level, choose one additional proficiency from a list thematic to your mandate:
[horizontal]
Knowledge:: One language, Arcana or History
Life:: Medicine or Herbalism Kit
Light:: Performance or Persuasion
Storm:: Athletics or Nature
Trickery:: Deception or Sleight of Hand
War:: Martial weapon or Heavy armor

== Divine Gift
Starting at 1st level, you gain a unique gift granted by your divine mandate.
You may use this feature a number of times equal to your Wisdom modifier (minimum of once) per long rest.

Guided Smite (War, Storm, Light, Trickery)::
When you take the Attack action, you may make an additional weapon attack as a bonus action. This attack deals extra radiant, thunder, lightning, or psychic damage (choose one).
10th Level: On a critical hit, you can make another weapon attack as part of the same action.
Protective Intercession (Life, Light, Knowledge)
When a creature within 30 feet takes damage, you can use your reaction to reduce the damage by 1d10 + your Wisdom modifier.
+
When you reach 10th Level, the creature gains temporary hit points equal to your {class-name-cleric} level.

Insightful Surge (Knowledge, Trickery)::
As a bonus action, you grant a creature that can see or hear you within 30 feet advantage on their next attack roll, ability check, or saving throw.

When you reach 10th Level, when using this ability, you also give a creature within range that can see or hear you, disadvantage on its next attack roll or ability check as you momentarily distract it or otherwise exploit a subtle weakness.

== Channel Divinity
Starting at 2nd level, you gain one of the following Channel Divinity options.

When you reach 6th level, the effects improve or gain additional features.

Channel Divinity: War Cry (War, Storm)::
As a bonus action, choose a number of creatures equal to your Wisdom modifier (minimum 1) that you can see within 30 feet.
Each target can immediately use their reaction to move up to half their speed without provoking an opportunity attack and make one weapon attack.
+
When you reach 6th Level, targets add your {class-name-cleric} level to their damage roll for this attack.

Channel Divinity: Luminous Infusion (Light, Storm)::
As an action, you cause divine light to flare in a 15-foot radius centered on yourself.
Choose one damage type: radiant, lightning, or fire. Until the start of your next turn, any creature that enters or ends its turn in the area or hits you with a melee attack takes 3 damage.
The damage increases by 2 each time your proficiency bonus increases.
+
When you reach 6th Level, allies in the aura deal +1d4 + your proficiency bonus damage of the chosen type on weapon attacks.

Channel Divinity: Revelatory Surge (Knowledge, Life, Trickery)::
You call forth a flash of divine understanding as an action that momentarily reveals hidden truths.
For 1 minute, you and allies in the area gain advantage on one Intelligence, Wisdom, or Charisma check of your choice, as divine clarity sharpens your senses and mind.
+
When you reach 6th Level, you and each creature of your choice within 30 feet have truesight for one minute.

Channel Divinity: Phantom’s Whim (Trickery, Knowledge)::
As a bonus action, you cloak a creature that you choose within 30 feet in illusions.
Until the start of your next turn, each target has partial cover and can take the Hide action as a bonus action.
+
When you reach 6th Level, the number of affected creatures increases by your proficiency bonus.

Channel Divinity: Aegis of Faith (Life, War)::
As an action, you conjure a divine shield around an ally within 30 feet.
Until the end of their next turn, the target adds your proficiency bonus to AC or resistance to necrotic or radiant damage.
+
When you reach 6th Level, the target also gains temporary hit points equal to 2d6 + your Wisdom modifier when you use this feature.

Channel Divinity: Echo of Command (Trickery, War)::
As a bonus action, choose a creature whose location you know within 30 feet.
+
If the creature is an ally, it can immediately use its reaction to make one weapon attack or cast a cantrip.
It adds your Wisdom modifier to the attack roll.
+
If the creature is an enemy, it must make a Wisdom saving throw.
On a failure, it uses its reaction to make a weapon attack or a spell attack with a cantrip, targeting a creature you choose.
+
When you reach 6th Level, when you use this ability, you may choose whether affected creatures can be frightened or charmed until the end of their next turn.

== Divine Strike or Potent Spellcasting
When you reach 8th level, choose one of the following:

Divine Strike.:: Your weapon attacks deal an extra 1d8 damage of a type appropriate to your mandate, increasing to 2d8 at 14th level.
+
Suggested Damage Types:
+
- Knowledge: Psychic
- Life: Radiant
- Light: Radiant
- Storm: Lightning or Thunder (choose one)
- Trickery: Poison or Acid (choose one)
- War: Bludgeoning, Piercing, or Slashing (choose one)

Potent Spellcasting.:: You add your Wisdom modifier to the damage you deal with {class-name-cleric} cantrips.

== Exalted Mandate
At 17th level, choose one matching your mandate.
You can use this feature once per long rest.

Avatar of War (War, Storm)::
When reduced to 0 hit points, you drop to 1 hit pointinstead and may use your reaction to make one weapon attack.
You also gain resistance to bludgeoning, piercing, and slashing damage for 1 minute.

Illuminated Soul (Light, Life)::
As an action, you emit a 30 foot aura for 1 minute.
Allies in the area gain advantage on saving throws against being blinded, charmed, or frightened and regain 1d6 HP at the start of their turns.

Shifting Facade (Trickery, Knowledge)::
The locations of anyone within 30 feet of you become difficult for enemies to determine for one minute, as all creatures that you choose, including you, seem to switch places with each other.
Enemies must succeed on a Wisdom saving throw or target a random creature when trying to attack any creature within range.

// end::subclass[]