= Arcanist
:doctype: article
:icons: font
:reproducible:
:revdate: May 1, 2025
:table-stripes: even
:stem:
:stylesdir: ../../../../css
:stylesheet: adoc-golo.css
:toc: left

// Custom attributes
include::../../../../attributes.adoc[]

// tag::subclass[]

[#wizard-subclass-arcanist-scholarly-speciality]
== Scholarly Specialty
When you take this archetype at 2nd level, choose one classical school of magic as your Scholarly Specialty: abjuration, conjuration, divination, enchantment, evocation, illusion, necromancy, or transmutation. The gold and time you must spend to copy spells from this school into your spellbook is halved. If a feature refers to your chosen school, it refers to the school selected in this feature.

[#wizard-subclass-arcanist-esoteric-talent]
== Esoteric Talent
Also at 2nd level, you gain one of the following benefits:

[#wizard-subclass-arcanist-esoteric-talent-bend-magic]
Bend Magic::
When you cast a wizard spell with an instantaneous duration that deals damage to an area, you can choose a number of creatures in the area that you can see equal to your Intelligence modifier (minimum one creature).
The chosen creatures take no damage from the spell.

[#wizard-subclass-arcanist-esoteric-talent-flash-of-insight]
Flash of Insight::
You can use a bonus action to roll a d20, record the result, and choose a creature you can see within 30 feet.
The next time that creature makes an attack roll, ability check, or saving throw, it takes that d20 result instead of rolling.
If you use this feature again before you finish a short rest, you must expend a spell slot of 1st-level or higher to do so.

[#wizard-subclass-arcanist-esoteric-talent-quick-step]
Quick Step::
After you cast a wizard spell of 1st-level or higher, you can immediately move up to 15 feet without provoking opportunity attacks or spending any of your normal movement.

[#wizard-subclass-arcanist-refined-learning]
== Refined Learning
At 6th level, choose one of the following benefits:

[#wizard-subclass-arcanist-refined-learning-arcane-armor]
Arcane Armor::
When you cast a wizard spell of 1st-level or higher, you store some of its magic to protect yourself, gaining temporary hit points equal to twice the level of the spell, or three times the spell's level if the spell is from your chosen school.
Instead of gaining these temporary hit points yourself, you can use your reaction to grant them to a creature you can see within 30 feet.

[#wizard-subclass-arcanist-refined-learning-energy-retention]
Energy Retention::
When you expend a spell slot of 2nd-level or higher to cast a wizard spell from your <<wizard-subclass-arcanist-scholarly-speciality,chosen school>>, you regain one expended spell slot.
The regained spell slot must be of a level no more than half the level of the expended spell slot.

[#wizard-subclass-arcanist-refined-learning-war-magic]
War Magic::
When you cast a wizard spell from your <<wizard-subclass-arcanist-scholarly-speciality,chosen school>> that deals damage, you deal additional damage equal to your Intelligence modifier (minimum +1) on the first damage roll for that spell.

[#wizard-subclass-arcanist-superior-talent]
== Superior Talent
At 10th level, choose one of the following benefits:

[#wizard-subclass-arcanist-superior-talent-perfect-control]
Perfect Control::
When concentrating on a wizard spell of your <<wizard-subclass-arcanist-scholarly-speciality,chosen school>>, you only need to roll to maintain concentration when you take damage from an attack, effect, or spell equal to or greater than your Intelligence score + your wizard level.

[#wizard-subclass-arcanist-superior-talent-secondary-learning]
Secondary Learning::
Choose a second school as your <<wizard-subclass-arcanist-scholarly-speciality>> and an additional feature from either <<wizard-subclass-arcanist-esoteric-talent>> or <<wizard-subclass-arcanist-refined-learning>>.

[#wizard-subclass-arcanist-superior-talent-splinter-spell]
Splinter Spell::
Once per rest, when you cast a wizard spell from your <<wizard-subclass-arcanist-scholarly-speciality,chosen school>> that only affects one creature, you can choose to affect an additional creature within range.

[#wizard-subclass-arcanist-specialized-mastery]
== Specialized Mastery
At 14th level, choose one of the following benefits:

[#wizard-subclass-arcanist-specialized-mastery-battle-hardiness]
Battle Hardiness::
When concentrating on a wizard spell from your <<wizard-subclass-arcanist-scholarly-speciality,chosen school>>, you reduce bludgeoning, piercing, and slashing damage you take by an amount equal to the level of the spell.

[#wizard-subclass-arcanist-specialized-mastery-heightened-potency]
Heightened Potency::
When you cast a wizard spell from your <<wizard-subclass-arcanist-scholarly-speciality,chosen school>>, it is always treated as though it were cast with a spell slot one level higher (maximum 9th-level) than the one you used, so long as you expended a spell slot to cast it.
The slot you use to cast the spell must still be at least equal to the level of the spell.

[#wizard-subclass-arcanist-specialized-mastery-precise-understanding]
Precise Understanding::
When you see a creature cast a spell from your <<wizard-subclass-arcanist-scholarly-speciality,chosen school>>, you automatically know what spell it's casting.
In addition, you have advantage on saving throws against spells.

// end::subclass[]