= Path of the Dragon
:doctype: book
:icons: font
:revdate: May 1, 2025
:stylesdir: ../../../../css
// Custom attributes
ifndef::env-github[]
include::../../../../attributes.adoc[]
endif::[]

// tag::subclass[]

{class-name-barbarian}s tap into primal powers, and a {class-name-barbarian} of this path taps into one of the most ancient and primeval of them all: the power of dragons.
Some say this path was born during the rage of dragons by mortals tapping into the primal rage as it washed across the world, others say that only those with latent dragon blood coursing through them can walk this path. What all can agree on is the result is a being to be feared.
As with most {class-name-barbarian} paths, ones following this path tend toward chaos, as they contain potent destructive power that paces at the edges of the cage, just waiting to be unleashed. Some, particularly those rare individuals that channel metallic colors, may be exceptions to this tendency.

== {subclass-name-barbarian-dragon} Features
When you choose this path at 3rd level, when you enter a rage, you can choose to make your Rage bonus damage deal elemental damage matching your draconic type (shown on the <<dreadnought-path-of-the-dragon-table,table>> below).

Additionally, when you enter a rage you can take on aspects of a draconic entity, growing vicious natural weapons as claws grow from your hands, fangs sprout from your maw, and a vicious lashing tail grows from your back.
Your claws deal 1d4 slashing damage.
Your fangs deal 1d8 piercing damage, and your lashing tail deals 1d6 bludgeoning damage and has the reach property.

Whenever you attack with one of these natural weapons using the Attack action on your turn, if you are not carrying any weapon or shield, you can make a single unarmed strike with your claws as a bonus action.

When you gain this feature, you pick a color, and gain resistance corresponding to the element type of that color on the following <<dreadnought-path-of-the-dragon-table>> table below while raging.

[#dreadnought-path-of-the-dragon-table]
.{subclass-name-barbarian-dragon} Elements
[%header,cols="1,1"]
|===
| Dragon Color | Element Type

| Black
| Acid

| Blue
| Lightning

| Green
| Poison

| Red
| Fire

| White
| Cold
|===

== Unleashed Brutality
Starting at 6th level, once during a rage, as an attack as part of the Attack action, you can unleash your rage into pure energy, exhaling a blast of elemental power. Creatures within a 15-foot cone must make a Dexterity saving throw. The DC of this saving throw is 8 + your proficiency modifier + your strength modifier. A creature takes 6d6 damage of the Elemental Type of your Dragon Color on a failed save. The damage and range of this breath weapon increases at 10th level (to 8d6 in a 30-foot cone), at 14th level (10d6 in a 45-foot cone), and at 18th level (12d6 in a 60 foot cone)

== Primal Weapons
Additionally at 6th level, the natural weapons you gain while raging now count as magical for the purpose of overcoming resistance and immunity to nonmagical attacks and damage.

== Dragonhide
Starting at 10th level, the marks of your Draconic path now remain outside of your rage, manifesting as heavy scales that grant you resistance to bludgeoning, piercing, and slashing damage from nonmagical sources even when you are not raging.
Additionally, you gain resistance to your dragon color’s elemental type even when you are not raging.

== Tyrant of the Skies
By 14th level, when you enter a rage, you can sprout massive dragon wings from your back.
If you are not wearing heavy armor, you gain a flying speed equal to your movement speed.

If you choose to manifest natural weapons and wings when you enter a rage, you can choose to entirely take on a draconic form while raging, becoming Large sized.
When you take on a full draconic form, you choose whether your equipment falls to the ground in your space, merges into your new form, or is worn by it.

// end::subclass[]