= Creating a Character
:doctype: book
:icons: font
:reproducible:
:revdate: May 1, 2025
:stem:
:stylesdir: ../css
:stylesheet: adoc-golo.css
:table-stripes: even
:toc: left
:toclevels: 1

// Custom attributes
ifndef::env-github[]
include::../attributes.adoc[]
endif::[]

// tag::content[]

As a player, begin by creating a character on the character sheet in the back of this book or a color-coded one at [LINK]. If you're using a paper copy, we recommend writing in an erasable medium like pencil.

. Think of a fantasy character concept that you'd like to play
. Determine ability scores
. Choose your class
. Choose your ancestry
. Choose your heritage
. Choose your background
. Choose your starting equipment
. Choose starting spells if applicable
. Add details like appearance, personality, etc. Consider drawing a picture of your character. It doesn't have to be fancy! It's just for your friends! (If you'd like to commission a professional portrait of your character, check the credits of this book for some great artists who love illustrating characters!)

== Determine Ability Scores
Use the following scores: 15, 14, 13, 12, 10, 8. Assign each of these numbers to one of your character's six abilities: Strength, Dexterity, Constitution, Intelligence, Wisdom, and Charisma. Then add 3 points to the character’s abilities, no more than two to any single ability. 

== Variant: Ability Score Point Buy
You have 27 points to spend on ability scores. The cost of each score is shown on the Ability Score Point Cost table. Then add 3 points to the character’s abilities, no more than two to any single ability.

.Ability Score Point Cost
[%header,cols="1,1"]
|===
| Score | Cost

|  8 | 0
|  9 | 1
| 10 | 2
| 11 | 3
| 12 | 4
| 13 | 5
| 14 | 7
| 15 | 9
|===

== Ability Modifiers
Your final ability scores determine your modifiers. Find your modifier by subtracting 10 from the ability score and dividing by 2 (round down). 

// end::content[]
