= {class-name-paladin}
:doctype: book
:icons: font
:revdate: May 1, 2025
:stylesdir: ../../../css
:toclevels: 4
// Custom attributes
:class-name-paladin: Vanguard
:subclass-name-paladin-devotion: Oath of Devotion
:subclass-name-paladin-silence: Oath of Silence
ifndef::env-github[]
include::../../../attributes.adoc[]
endif::[]

// tag::class[]

{class-name-paladin}s channel divine strength, standing as unyielding champions of causes greater than themselves.

== Class Features
As a {class-name-paladin}, you gain the following class features.

=== Hit Points
[horizontal]
Hit Dice:: 1d10 per {class-name-paladin} level
Hit Points at 1st Level:: 10 + your Constitution modifier
Hit Points at Higher Levels:: 1d10 (or 6) + your Constitution modifier per {class-name-paladin} level after 1st

=== Proficiencies
[horizontal]
Armor:: All armor, shields
Weapons:: Simple weapons, martial weapons
Tools:: None
Saving Throws:: Wisdom, Charisma
Skills:: Choose two from Athletics, Insight, Intimidation, Medicine, Persuasion, and Religion

=== Equipment
You start with the following equipment, in addition to the equipment granted by your background:

- (a) a martial weapon and a shield or (b) two martial weapons
- (a) five javelins or (b) any simple melee weapon
- (a) a priest’s pack or (b) an explorer’s pack
- Chain mail and a holy symbol

[#vanguard-table]
.The {class-name-paladin} (table)
[%header,cols="1,2,4,^1,^1,^1,^1,^1"]
|===
| Level | Proficiency Bonus | Features | 1st | 2nd | 3rd | 4th | 5th

|  1st | +2
| <<vanguard-feature-divine-sense>>, <<vanguard-feature-lay-on-hands>>
| - | - | - | - | -

|  2nd | +2
| <<vanguard-feature-fighting-style>>, <<vanguard-feature-spellcasting>>, <<vanguard-feature-divine-smite>>
| 2 | - | - | - | -

|  3rd | +2
| <<vanguard-feature-divine-health>>, <<vanguard-feature-oath-of-duty>>
| 3 | - | - | - | -

|  4th | +2
| <<vanguard-feature-asi>>
| 3 | - | - | - | -

|  5th | +3
| <<vanguard-feature-extra-attack>>
| 4 | 2 | - | - | -

|  6th | +3
| <<vanguard-feature-aura-of-protection>>
| 4 | 2 | - | - | -

|  7th | +3
| <<vanguard-feature-oath-of-duty>> feature
| 4 | 3 | - | - | -

|  8th | +3
| <<vanguard-feature-asi>>
| 4 | 3 | - | - | -

|  9th | +4
| -
| 4 | 3 | 2 | - | -

| 10th | +4
| <<vanguard-feature-aura-of-courage>>
| 4 | 3 | 2 | - | -

| 11th | +4
| <<vanguard-feature-improved-divine-smite>>
| 4 | 3 | 3 | - | -

| 12th | +4
| <<vanguard-feature-asi>>
| 4 | 3 | 3 | - | -

| 13th | +5
| -
| 4 | 3 | 3 | 1 | -

| 14th | +5
| <<vanguard-feature-cleansing-touch>>
| 4 | 3 | 3 | 1 | -

| 15th | +5
| <<vanguard-feature-oath-of-duty>> feature
| 4 | 3 | 3 | 2 | -

| 16th | +5
| <<vanguard-feature-asi>>
| 4 | 3 | 3 | 2 | -

| 17th | +6
| -
| 4 | 3 | 3 | 3 | 1

| 18th | +6
| Aura improvements
| 4 | 3 | 3 | 3 | 1

| 19th | +6
| <<vanguard-feature-asi>>
| 4 | 3 | 3 | 3 | 2

| 20th | +6
| <<vanguard-feature-oath-of-duty>> feature
| 4 | 3 | 3 | 3 | 2
|===

[#vanguard-feature-divine-sense]
== Divine Sense
The presence of strong evil registers on your senses like a noxious odor, and powerful good rings like heavenly music in your ears. As an action, you can open your awareness to detect such forces. Until the end of your next turn, you know the location of any celestial, fiend, or undead within 60 feet of you that is not behind total cover. You know the type (celestial, fiend, or undead) of any being whose presence you sense, but not its identity (the vampire Count Strahd von Zarovich, for instance). Within the same radius, you also detect the presence of any place or object that has been consecrated or desecrated, as with the Hallow spell.
You can use this feature a number of times equal to 1 + your Charisma modifier. When you finish a long rest, you regain all expended uses.

[#vanguard-feature-lay-on-hands]
== Lay on Hands
Your blessed touch can heal wounds. You have a pool of healing power that replenishes when you take a long rest. With that pool, you can restore a total number of hit points equal to your {class-name-paladin} level stem:[× 5].

As an action, you can touch a creature and draw power from the pool to restore a number of hit points to that creature, up to the maximum amount remaining in your pool.

Alternatively, you can expend 5 hit points from your pool of healing to cure the target of one disease or neutralize one poison affecting it.
You can cure multiple diseases and neutralize multiple poisons with a single use of Lay on Hands, expending hit points separately for each one.

This feature has no effect on undead and constructs.

[#vanguard-feature-fighting-style]
== Fighting Style
At 2nd level, you adopt a style of fighting as your specialty.
Choose one of the following options.
You can’t take a Fighting Style option more than once, even if you later get to choose again.

[#vanguard-feature-fighting-style-defense]
Defense::
While you are wearing armor, you gain a +1 bonus to AC.

[#vanguard-feature-fighting-style-dueling]
Dueling::
When you are wielding a melee weapon in one hand and no other weapons, you gain a +2 bonus to damage rolls with that weapon.

[#vanguard-feature-fighting-style-gwf]
Great Weapon Fighting::
When you roll a 1 or 2 on a damage die for an attack you make with a melee weapon that you are wielding with two hands, you can reroll the die and must use the new roll.
The weapon must have the two-handed or versatile property for you to gain this benefit.

[#vanguard-feature-lay-fighting-style-protection]
Protection::
When a creature you can see attacks a target other than you that is within 5 feet of you, you can use your reaction to impose disadvantage on the attack roll.
You must be wielding a shield.

[#vanguard-feature-spellcasting]
== Spellcasting
By 2nd level, you have learned to draw on divine magic through meditation and prayer to cast spells as a Cleric does.

=== Preparing and Casting Spells
The <<vanguard-table,{class-name-paladin} table>> shows how many spell slots you have to cast your spells.
To cast one of your {class-name-paladin} spells of 1st level or higher, you must expend a slot of the spell’s level or higher.
You regain all expended spell slots when you finish a long rest.

You prepare the list of {class-name-paladin} spells that are available for you to cast, choosing from the <<spell-list-vanguard,{class-name-paladin} spell list>>.
When you do so, choose a number of {class-name-paladin} spells equal to your Charisma modifier + half your {class-name-paladin} level, rounded down (minimum of one spell).
The spells must be of a level for which you have spell slots.

For example, if you are a 5th-level {class-name-paladin}, you have four 1st-level and two 2nd-level spell slots.
With a Charisma of 14, your list of prepared spells can include four spells of 1st or 2nd level, in any combination.
If you prepare the 1st-level spell Cure Wounds, you can cast it using a 1st-level or a 2nd-level slot.
Casting the spell doesn’t remove it from your list of prepared spells.

You can change your list of prepared spells when you finish a long rest.
Preparing a new list of {class-name-paladin} spells requires time spent in prayer and meditation: at least 1 minute per spell level for each spell on your list.

=== Spellcasting Ability
Charisma is your spellcasting ability for your {class-name-paladin} spells, since their power derives from the strength of your convictions.
You use your Charisma whenever a spell refers to your spellcasting ability.
In addition, you use your Charisma modifier when setting the saving throw DC for a {class-name-paladin} spell you cast and when making an attack roll with one.

[horizontal]
Spell save DC:: = 8 + your proficiency bonus + your Charisma modifier
Spell attack modifier:: = your proficiency bonus + your Charisma modifier

=== Spellcasting Focus
You can use a holy symbol as a spellcasting focus for your {class-name-paladin} spells.

[#vanguard-feature-divine-smite]
== Divine Smite
Starting at 2nd level, when you hit a creature with a melee weapon attack, you can expend one spell slot to deal radiant damage to the target, in addition to the weapon’s damage. The extra damage is 2d8 for a 1st-level spell slot, plus 1d8 for each spell level higher than 1st, to a maximum of 5d8. The damage increases by 1d8 if the target is an undead or a fiend.

[#vanguard-feature-divine-health]
== Divine Health
By 3rd level, the divine magic flowing through you makes you immune to disease.

[#vanguard-feature-oath-of-duty]
== Oath of Duty
When you reach 3rd level, you swear the <<vanguard-subclasses,oath>> that binds you as a {class-name-paladin} forever.
Up to this time you have been in a preparatory stage, committed to the path but not yet sworn to it.
Your choice grants you features at 3rd level and again at 7th, 15th, and 20th level.
Those features include oath spells and the Channel Divinity feature.

[#vanguard-feature-oath-of-duty-oath-spells]
=== Oath Spells
Each oath has a list of associated spells. You gain access to these spells at the levels specified in the oath description.
Once you gain access to an oath spell, you always have it prepared.
Oath spells don’t count against the number of spells you can prepare each day.

If you gain an oath spell that doesn’t appear on the {class-name-paladin} spell list, the spell is nonetheless a {class-name-paladin} spell for you.

[#vanguard-feature-oath-of-duty-channel-divinity]
=== Channel Divinity
Your oath allows you to channel divine energy to fuel magical effects.
Each Channel Divinity option provided by your oath explains how to use it.

When you use your Channel Divinity, you choose which option to use.
You must then finish a short or long rest to use your Channel Divinity again.

Some Channel Divinity effects require saving throws.
When you use such an effect from this class, the DC equals your {class-name-paladin} spell save DC.

[#vanguard-feature-asi]
== Ability Score Improvement
When you reach 4th level, and again at 8th, 12th, 16th, and 19th level, you can increase one ability score of your choice by 2, or you can increase two ability scores of your choice by 1.
As normal, you can’t increase an ability score above 20 using this feature.

[#vanguard-feature-extra-attack]
== Extra Attack
Beginning at 5th level, you can attack twice, instead of once, whenever you take the Attack action on your turn.

[#vanguard-feature-aura-of-protection]
== Aura of Protection
Starting at 6th level, whenever you or a friendly creature within 10 feet of you must make a saving throw, the creature gains a bonus to the saving throw equal to your Charisma modifier (with a minimum bonus of +1). You must be conscious to grant this bonus.

At 18th level, the range of this aura increases to 30 feet.

[#vanguard-feature-aura-of-courage]
== Aura of Courage
Starting at 10th level, you and friendly creatures within 10 feet of you can’t be frightened while you are conscious.

At 18th level, the range of this aura increases to 30 feet.

[#vanguard-feature-improved-divine-smite]
== Improved Divine Smite
By 11th level, you are so suffused with righteous might that all your melee weapon strikes carry divine power with them.
Whenever you hit a creature with a melee weapon, the creature takes an extra 1d8 radiant damage.
If you also use your Divine Smite with an attack, you add this damage to the extra damage of your Divine Smite.

[#vanguard-feature-cleansing-touch]
== Cleansing Touch
Beginning at 14th level, you can use your action to end one spell on yourself or on one willing creature that you touch.
You can use this feature a number of times equal to your Charisma modifier (a minimum of once).
You regain expended uses when you finish a long rest.

[#vanguard-subclasses]
== Oaths of Duty
Becoming a {class-name-paladin} involves taking vows that commit the {class-name-paladin} to the cause of righteousness, an active path of fighting wickedness.
The final oath, taken when he or she reaches 3rd level, is the culmination of all the {class-name-paladin}'s training.
Some characters with this class don’t consider themselves true {class-name-paladin}s until they have reached 3rd level and made this oath.
For others, the actual swearing of the oath is a formality, an official stamp on what has always been true in the {class-name-paladin}'s heart.

[#vanguard-subclasse-oath-of-devotion]
=== {subclass-name-paladin-devotion}
include::Oaths_of_Duty/Oath_of_Devotion.adoc[leveloffset=+2, tag=subclass]

=== {subclass-name-paladin-silence}
include::Oaths_of_Duty/Oath_of_Silence.adoc[leveloffset=+2, tag=subclass]

== Breaking Your Oath
A {class-name-paladin} tries to hold to the highest standards of conduct, but even the most virtuous {class-name-paladin} is fallible.
Sometimes the right path proves too demanding, sometimes a situation calls for the lesser of two evils, and sometimes the heat of emotion causes a {class-name-paladin} to transgress his or her oath.

A {class-name-paladin} who has broken a vow typically seeks absolution from a Cleric who shares his or her faith or from another {class-name-paladin} of the same order.
The {class-name-paladin} might spend an all- night vigil in prayer as a sign of penitence, or undertake a fast or similar act of self-denial.
After a rite of confession and forgiveness, the {class-name-paladin} starts fresh.

If a {class-name-paladin} willfully violates his or her oath and shows no sign of repentance, the consequences can be more serious.
At the GM’s discretion, an impenitent {class-name-paladin} might be forced to abandon this class and adopt another.

// end::class[]

// tag::spell-list

[#spell-list-vanguard]
=== {class-name-paladin} Spells

include::../../../04_Rules_of_Magic/Spell_Lists/Vanguard_Spells.adoc[leveloffset=+2, tag=spell-list]

// end::spell-list

// tag::spell-descriptions

[#spell-descriptions-vanguard]
=== {class-name-paladin} Spell Descriptions

include::../../../04_Rules_of_Magic/Spell_Lists/Vanguard_Spells.adoc[leveloffset=+2, tag=spell-descriptions]

// end::spell-descriptions
