= Spellcasting
:doctype: book
:icons: font
:revdate: May 1, 2025
:stylesdir: ../css
:toclevels: 3
// Custom attributes
ifndef::env-github[]
include::../attributes.adoc[]
endif::[]

// tag::spellcasting[]

Magic rules fantasy gaming worlds, often as spells.
This section covers spellcasting.
Character classes and monsters have unique spell learning and preparation methods.
Regardless of origin, spells follow these rules.

== What Is a Spell?
A spell is a discrete magical effect, a single shaping of magical energies in the multiverse.
Casting a spell involves plucking, pinning, vibrating, and releasing invisible strands of magic to unleash the desired effect, usually in seconds.
Spells can be versatile tools, weapons, or protective wards, dealing damage, undoing it, imposing or removing conditions, draining life energy, or restoring it.
Thousands of spells have been created throughout history, many forgotten.
Some might be recorded in ancient spellbooks or trapped in the minds of dead gods, while others could be reinvented by powerful characters.

== Concentration
Some spells require concentration to maintain their magic. If you lose concentration, the spell ends.
If a spell needs concentration, its Duration entry specifies how long you can concentrate.
You can end concentration anytime. Normal activity doesn’t interfere.
The following can break concentration:

Casting another spell that requires concentration.:: You lose concentration on a spell if you cast another spell that requires concentration.
You can’t concentrate on two spells at once.
Taking damage.:: Whenever you take damage while concentrating on a spell, make a Constitution saving throw to maintain concentration.
The DC is 10 or half the damage, whichever is higher.
If you take damage from multiple sources, make a separate saving throw for each.
Being incapacitated or killed.:: You lose concentration on a spell if incapacitated or die.
The GM may also require a DC 10 Constitution saving throw to maintain concentration on a spell due to certain environmental phenomena, like a crashing wave on a storm-tossed ship.

// end::spellcasting[]