= Wizard
:doctype: article
:icons: font
:reproducible:
:revdate: May 1, 2025
:table-stripes: even
:stem:
:stylesdir: ../../../css
:stylesheet: adoc-golo.css
:toc: left
:toclevels: 4

// Custom attributes
include::../../../attributes.adoc[]

// tag::class[]

Through study, discipline, and boundless curiosity, {class-name-wizard}s unravel the secrets of magic, bending reality through sheer knowledge.

== Class Features
As a {class-name-wizard}, you gain the following class features.

=== Hit Points
[horizontal]
Hit Dice:: 1d6 per {class-name-wizard} level
Hit Points at 1st Level:: 6 + your Constitution modifier
Hit Points at Higher Levels:: 1d6 (or 4) + your Constitution modifier per {class-name-wizard} level after 1st

=== Proficiencies
[horizontal]
Armor:: None
Weapons:: Daggers, darts, slings, quarterstaffs, light crossbows
Tools:: None
Saving Throws:: Intelligence, Wisdom
Skills:: Choose two from Arcana, History, Insight, Investigation, Medicine, and Religion

=== Equipment
You start with the following equipment, in addition to the equipment granted by your background:

- (a) a quarterstaff or (b) a dagger
- (a) a component pouch or (b) an arcane focus
- (a) a scholar’s pack or (b) an explorer’s pack
- A spellbook

[#wizard-table]
.The {class-name-wizard} (table)
[%header,cols="3,6,^5,^2,^2,^2,^2,^2,^2,^2,^2,^2,8"]
|===
| Level | Proficiency Bonus | Cantrips Known | 1st | 2nd | 3rd | 4th | 5th | 6th | 7th | 8th | 9th | Features

| 1st
| +2
| 3
| 2
| -
| -
| -
| -
| -
| -
| -
| -
| <<wizard-feature-spellcasting>>, <<wizard-feature-arcane-recovery>>

| 2nd
| +2
| 3
| 3
| -
| -
| -
| -
| -
| -
| -
| -
| <<wizard-feature-arcane-tradition>>

| 3rd
| +2
| 3
| 4
| 2
| -
| -
| -
| -
| -
| -
| -
| -

| 4th
| +2
| 4
| 4
| 3
| -
| -
| -
| -
| -
| -
| -
| <<wizard-feature-asi>>

| 5th
| +3
| 4
| 4
| 3
| 2
| -
| -
| -
| -
| -
| -
| -

| 6th
| +3
| 4
| 4
| 3
| 3
| -
| -
| -
| -
| -
| -
| Arcane Tradition feature

| 7th
| +3
| 4
| 4
| 3
| 3
| 1
| -
| -
| -
| -
| -
| -

| 8th
| +3
| 4
| 4
| 3
| 3
| 2
| -
| -
| -
| -
| -
| <<wizard-feature-asi>>

| 9th
| +4
| 4
| 4
| 3
| 3
| 3
| 1
| -
| -
| -
| -
| -

| 10th
| +4
| 5
| 4
| 3
| 3
| 3
| 2
| -
| -
| -
| -
| Arcane Tradition feature

| 11th
| +4
| 5
| 4
| 3
| 3
| 3
| 2
| 1
| -
| -
| -
| -

| 12th
| +4
| 5
| 4
| 3
| 3
| 3
| 2
| 1
| -
| -
| -
| <<wizard-feature-asi>>

| 13th
| +5
| 5
| 4
| 3
| 3
| 3
| 2
| 1
| 1
| -
| -
| -

| 14th
| +5
| 5
| 4
| 3
| 3
| 3
| 2
| 1
| 1
| -
| -
| Arcane Tradition feature

| 15th
| +5
| 5
| 4
| 3
| 3
| 3
| 2
| 1
| 1
| 1
| -
| -

| 16th
| +5
| 5
| 4
| 3
| 3
| 3
| 2
| 1
| 1
| 1
| -
| <<wizard-feature-asi>>

| 17th
| +6
| 5
| 4
| 3
| 3
| 3
| 2
| 1
| 1
| 1
| 1
| -

| 18th
| +6
| 5
| 4
| 3
| 3
| 3
| 3
| 1
| 1
| 1
| 1
| <<wizard-feature-spell-mastery>>

| 19th
| +6
| 5
| 4
| 3
| 3
| 3
| 3
| 2
| 1
| 1
| 1
| <<wizard-feature-asi>>

| 20th
| +6
| 5
| 4
| 3
| 3
| 3
| 3
| 2
| 2
| 1
| 1
| <<wizard-feature-signature-spells>>
|===

[#wizard-feature-spellcasting]
== Spellcasting
As a student of arcane magic, you have a spellbook containing spells that show the first glimmerings of your true power.

=== Cantrips
At 1st level, you know three cantrips of your choice from the {class-name-wizard} spell list. You learn additional {class-name-wizard} cantrips of your choice at higher levels, as shown in the Cantrips Known column of the <<wizard-table,{class-name-wizard} table>>.

=== Spellbook
At 1st level, you have a spellbook containing six 1st-level {class-name-wizard} spells of your choice. Your spellbook is the repository of the {class-name-wizard} spells you know, except your cantrips, which are fixed in your mind.

=== Your Spellbook
The spells you add to your spellbook reflect your arcane research and intellectual breakthroughs about the multiverse. You might find other spells during adventures, like a scroll in an evil {class-name-wizard}’s chest or a dusty tome in an ancient library.

Copying a Spell into the Book.:: When you find a {class-name-wizard} spell of 1st level or higher, you can add it to your spellbook if it is of a spell level you can prepare and if you can spare the time to decipher and copy it.
Copying a spell into your spellbook involves reproducing its basic form and deciphering its unique notation. Practice until you understand the sounds and gestures, then transcribe it using your notation.
Each level takes 2 hours and costs 50 gp. This includes material components and fine inks for experimentation and recording. Once mastered, you can prepare the spell like other spells.

Replacing the Book.:: You can copy a spell from your own spellbook into another book—for example, if you want to make a backup copy of your spellbook. This is just like copying a new spell into your spellbook, but faster and easier, since you understand your own notation and already know how to cast the spell. You need spend only 1 hour and 10 gp for each level of the copied spell.
If you lose your spellbook, you can use the same procedure to transcribe the spells that you have prepared into a new spellbook. Filling out the remainder of your spellbook requires you to find new spells to do so, as normal. For this reason, many {class-name-wizard}s keep backup spellbooks in a safe place.

The Book’s Appearance.:: Your spellbook is a unique compilation of spells, with its own decorative flourishes and margin notes.
It might be a plain, functional leather volume that you received as a gift from your master, a finely bound gilt-edged tome you found in an ancient library, or even a loose collection of notes scrounged together after you lost your previous spellbook in a mishap.

=== Preparing and Casting Spells
The <<wizard-table,{class-name-wizard} table>> shows how many spell slots you have to cast your spells of 1st level and higher. To cast one of these spells, you must expend a slot of the spell’s level or higher. You regain all expended spell slots when you finish a long rest.
You prepare the list of {class-name-wizard} spells that are available for you to cast. To do so, choose a number of {class-name-wizard} spells from your spellbook equal to your Intelligence modifier + your {class-name-wizard} level (minimum of one spell). The spells must be of a level for which you have spell slots.
For example, if you’re a 3rd-level {class-name-wizard}, you have four 1st-level and two 2nd-level spell slots. With an Intelligence of 16, your list of prepared spells can include six spells of 1st or 2nd level, in any combination, chosen from your spellbook. If you prepare the 1st-level spell Magic Missile, you can cast it using a 1st-level or a 2nd-level slot. Casting the spell doesn’t remove it from your list of prepared spells.
You can change your list of prepared spells when you finish a long rest. Preparing a new list of {class-name-wizard} spells requires time spent studying your spellbook and memorizing the incantations and gestures you must make to cast the spell: at least 1 minute per spell level for each spell on your list.

=== Spellcasting Ability
Intelligence is your spellcasting ability for your {class-name-wizard} spells, since you learn your spells through dedicated study and memorization. You use your Intelligence whenever a spell refers to your spellcasting ability. In addition, you use your Intelligence modifier when setting the saving throw DC for a {class-name-wizard} spell you cast and when making an attack roll with one.

[horizontal]
Spell save DC:: = 8 + your proficiency bonus + your Intelligence modifier
Spell attack modifier:: = your proficiency bonus + your Intelligence modifier

=== Ritual Casting
You can cast a {class-name-wizard} spell as a ritual if that spell has the ritual tag and you have the spell in your spellbook. You don’t need to have the spell prepared.

=== Spellcasting Focus
You can use an arcane focus as a spellcasting focus for your {class-name-wizard} spells.

=== Learning Spells of 1st Level and Higher
Each time you gain a {class-name-wizard} level, you can add two {class-name-wizard} spells of your choice to your spellbook for free. Each of these spells must be of a level for which you have spell slots, as shown on the <<wizard-table,{class-name-wizard} table>>. On your adventures, you might find other spells that you can add to your spellbook (see the “Your Spellbook” sidebar).

[#wizard-feature-arcane-recovery]
== Arcane Recovery
You have learned to regain some of your magical energy by studying your spellbook. Once per day when you finish a short rest, you can choose expended spell slots to recover. The spell slots can have a combined level that is equal to or less than half your {class-name-wizard} level (rounded up), and none of the slots can be 6th level or higher.
For example, if you’re a 4th-level {class-name-wizard}, you can recover up to two levels worth of spell slots. You can recover either a 2nd-level spell slot or two 1st-level spell slots.

[#wizard-feature-arcane-tradition]
== Arcane Tradition
When you reach 2nd level, you choose an <<wizard-subclasses,arcane tradition>>. Your choice grants you features at 2nd level and again at 6th, 10th, and 14th level.

[#wizard-feature-asi]
== Ability Score Improvement
When you reach 4th level, and again at 8th, 12th, 16th, and 19th level, you can increase one ability score of your choice by 2, or you can increase two ability scores of your choice by 1. As normal, you can’t increase an ability score above 20 using this feature.

[#wizard-feature-spell-mastery]
== Spell Mastery
At 18th level, you have achieved such mastery over certain spells that you can cast them at will. Choose a 1st-level {class-name-wizard} spell and a 2nd-level {class-name-wizard} spell that are in your spellbook. You can cast those spells at their lowest level without expending a spell slot when you have them prepared. If you want to cast either spell at a higher level, you must expend a spell slot as normal.

By spending 8 hours in study, you can exchange one or both of the spells you chose for different spells of the same levels.

[#wizard-feature-signature-spells]
== Signature Spells
When you reach 20th level, you gain mastery over two powerful spells and can cast them with little effort. Choose two 3rd-level {class-name-wizard} spells in your spellbook as your signature spells. You always have these spells prepared, they don’t count against the number of spells you have prepared, and you can cast each of them once at 3rd level without expending a spell slot. When you do so, you can’t do so again until you finish a short or long rest.
If you want to cast either spell at a higher level, you must expend a spell slot as normal.

[#wizard-subclasses]
== Arcane Traditions
The study of Wizardry, dating back to early magical discoveries, is prevalent in fantasy gaming worlds with diverse magical traditions.

The most common arcane traditions revolve around the eight schools of magic, cataloged by {class-name-wizard}s throughout history: Abjuration, Conjuration, Divination, Enchantment, Evocation, Illusion, Necromancy and Transmutation. These schools can be literal institutions, like the School of Illusion, or academic departments with rival faculties. Even {class-name-wizard}s who train apprentices use the school division as a learning device, as each school requires mastery of different techniques.

[#wizard-subclass-arcanist]
=== {subclass-name-wizard-arcanist}
include::Arcane_Traditions/Arcanist.adoc[leveloffset=+2, tag=subclass]

[#wizard-subclass-theurge]
=== {subclass-name-wizard-theurge}
include::Arcane_Traditions/Theurge.adoc[leveloffset=+2, tag=subclass]

// end::class[]

// tag::spell-list

[#spell-list-wizard]
=== {class-name-wizard} Spells

include::../../../04_Rules_of_Magic/Spell_Lists/Wizard_Spells.adoc[leveloffset=+2, tag=spell-list]

// end::spell-list

// tag::spell-descriptions

[#spell-descriptions-wizard]
=== {class-name-wizard} Spell Descriptions

include::../../../04_Rules_of_Magic/Spell_Lists/Wizard_Spells.adoc[leveloffset=+2, tag=spell-descriptions]

// end::spell-descriptions
