= Ancestries
:doctype: book
:icons: font
:revdate: May 1, 2025
:stem:
:stylesdir: ../../css
:toc: left
// Custom attributes
ifndef::env-github[]
include::../../attributes.adoc[]
endif::[]

// tag::ancestries[]

== Ancestral Traits
The description of each ancestry includes inherited traits that are common to members of that ancestry. The following entries appear among the traits of most ancestries. Some ancestries have variants with traits of the parent ancestry and variant-specific traits.

Age::
The age entry notes when an ancestry member becomes an adult and its expected lifespan. This helps decide your character’s age at the game’s start. You can choose any age, which may explain ability scores. For instance, a young or old character might have low Strength or Constitution, while advanced age could explain high Intelligence or Wisdom.

Size::
Characters of most ancestries are Medium, between 4 and 8 feet tall. A few ancestries are Small (2 to 4 feet tall), and some game rules may affect them differently. Small characters may struggle with heavy weapons, as explained in “Equipment.”

Speed::
Your speed determines how far you can move when traveling (“Adventuring”) and fighting (“Combat”).

Languages::
By virtue of your ancestry, your character can speak, read, and write certain languages.

[#ancestry-dwarf]
== Dwarf
include::Ancestries/Dwarf.adoc[leveloffset=+1, tag=ancestry]

[#ancestry-elf]
== Elf
include::Ancestries/Elf.adoc[leveloffset=+1, tag=ancestry]

// end::ancestries[]