= {class-name-barbarian}
:doctype: book
:icons: font
:revdate: May 1, 2025
:stylesdir: ../../../css
:toclevels: 4
// Custom attributes
:class-name-barbarian: Dreadnought
:subclass-name-barbarian-berserker: Path of the Berserker
:subclass-name-barbarian-dragon: Path of the Dragon
ifndef::env-github[]
include::../../../attributes.adoc[]
endif::[]

// tag::class[]

Unstoppable in battle, {class-name-barbarian}s draw strength from raw emotion, turning fury and resilience into unmatched combat prowess.

== Class Features
As a {class-name-barbarian}, you gain the following class features.

=== Hit Points
[horizontal]
Hit Dice:: 1d12 per {class-name-barbarian} level
Hit Points at 1st Level:: 12 + your Constitution modifier
Hit Points at Higher Levels:: 1d12 (or 7) + your Constitution modifier per {class-name-barbarian} level after 1st

=== Proficiencies
[horizontal]
Armor:: Light armor, medium armor, shields
Weapons:: Simple weapons, martial weapons
Tools:: None
Saving Throws:: Strength, Constitution
Skills:: Choose two from Animal Handling, Athletics, Intimidation, Nature, Perception, and Survival

=== Equipment
You start with the following equipment, in addition to the equipment granted by your background:

- (a) a greataxe or (b) any martial melee weapon
- (a) two handaxes or (b) any simple weapon
- An explorer’s pack and four javelins

[#dreadnought-table]
.The {class-name-barbarian} (table)
[%header,cols="1,2,4,^1,1"]
|===
| Level | Proficiency Bonus | Features | Rages | Rage Damage

| 1st
| +2
| <<dreadnought-feature-rage>>, <<dreadnought-feature-unarmored-defense>>
| 2
| +2

| 2nd
| +2
| <<dreadnought-feature-reckless-attack>>, <<dreadnought-feature-danger-sense>>
| 2
| +2

| 3rd
| +2
| <<dreadnought-feature-path>>
| 3
| +2

| 4th
| +2
| <<dreadnought-feature-asi>>
| 3
| +2

| 5th
| +3
| <<dreadnought-feature-extra-attack>>, <<dreadnought-feature-fast-movement>>
| 3
| +2

| 6th
| +3
| Path feature
| 4
| +2

| 7th
| +3
| <<dreadnought-feature-feral-instinct>>
| 4
| +2

| 8th
| +3
| <<dreadnought-feature-asi>>
| 4
| +2

| 9th
| +4
| <<dreadnought-feature-brutal-critical>> (1 die)
| 4
| +3

| 10th
| +4
| Path feature
| 4
| +3

| 11th
| +4
| <<dreadnought-feature-relentless-rage>>
| 4
| +3

| 12th
| +4
| <<dreadnought-feature-asi>>
| 5
| +3

| 13th
| +5
| <<dreadnought-feature-brutal-critical>> (2 dice)
| 5
| +3

| 14th
| +5
| Path feature
| 5
| +3

| 15th
| +5
| <<dreadnought-feature-persistent-rage>>
| 5
| +3

| 16th
| +5
| <<dreadnought-feature-asi>>
| 5
| +4

| 17th
| +6
| <<dreadnought-feature-brutal-critical>> (3 dice)
| 6
| +4

| 18th
| +6
| <<dreadnought-feature-indomitable-might>>
| 6
| +4

| 19th
| +6
| <<dreadnought-feature-asi>>
| 6
| +4

| 20th
| +6
| <<dreadnought-feature-primal-champion>>
| Unlimited
| +4
|===

[#dreadnought-feature-rage]
== Rage
In battle, you fight with primal ferocity. On your turn, you can enter a rage as a bonus action.
While raging, you gain the following benefits if you aren’t wearing heavy armor:

- You have advantage on Strength checks and Strength saving throws.
- When you make a melee weapon attack using Strength, you gain a bonus to the damage roll that increases as you gain levels as a {class-name-barbarian}, as shown in the Rage Damage column of the <<dreadnought-table,{class-name-barbarian} table>>.
- You have resistance to bludgeoning, piercing, and slashing damage.

If you are able to cast spells, you can’t cast them or concentrate on them while raging.
Your rage lasts for 1 minute. It ends early if you are knocked unconscious or if your turn ends and you haven’t attacked a hostile creature since your last turn or taken damage since then. You can also end your rage on your turn as a bonus action.
Once you have raged the number of times shown for your {class-name-barbarian} level in the Rages column of the <<dreadnought-table,{class-name-barbarian} table>>, you must finish a long rest before you can rage again.

[#dreadnought-feature-unarmored-defense]
== Unarmored Defense
While you are not wearing any armor, your Armor Class equals 10 + your Dexterity modifier + your Constitution modifier. You can use a shield and still gain this benefit.

[#dreadnought-feature-reckless-attack]
== Reckless Attack
Starting at 2nd level, you can throw aside all concern for defense to attack with fierce desperation. When you make your first attack on your turn, you can decide to attack recklessly. Doing so gives you advantage on melee weapon attack rolls using Strength during this turn, but attack rolls against you have advantage until your next turn.

[#dreadnought-feature-danger-sense]
== Danger Sense
At 2nd level, you gain an uncanny sense of when things nearby aren’t as they should be, giving you an edge when you dodge away from danger.
You have advantage on Dexterity saving throws against effects that you can see, such as traps and spells. To gain this benefit, you can’t be blinded, deafened, or incapacitated.

[#dreadnought-feature-path]
== {class-name-barbarian} Path
At 3rd level, you choose a <<dreadnought-subclasses,path>> that shapes the nature of your rage. Your choice grants you features at 3rd level and again at 6th, 10th, and 14th levels.

[#dreadnought-feature-asi]
== Ability Score Improvement
When you reach 4th level, and again at 8th, 12th, 16th, and 19th level, you can increase one ability score of your choice by 2, or you can increase two ability scores of your choice by 1. As normal, you can’t increase an ability score above 20 using this feature.

[#dreadnought-feature-extra-attack]
== Extra Attack
Beginning at 5th level, you can attack twice, instead of once, whenever you take the Attack action on your turn.

[#dreadnought-feature-fast-movement]
== Fast Movement
Starting at 5th level, your speed increases by 10 feet while you aren’t wearing heavy armor.

[#dreadnought-feature-feral-instinct]
== Feral Instinct
By 7th level, your instincts are so honed that you have advantage on initiative rolls.
Additionally, if you are surprised at the beginning of combat and aren’t incapacitated, you can act normally on your first turn, but only if you enter your rage before doing anything else on that turn.

[#dreadnought-feature-brutal-critical]
== Brutal Critical
Beginning at 9th level, you can roll one additional weapon damage die when determining the extra damage for a critical hit with a melee attack.
This increases to two additional dice at 13th level and three additional dice at 17th level.

[#dreadnought-feature-relentless-rage]
== Relentless Rage
Starting at 11th level, your rage can keep you fighting despite grievous wounds. If you drop to 0 hit points while you’re raging and don’t die outright, you can make a DC 10 Constitution saving throw. If you succeed, you drop to 1 hit point instead.
Each time you use this feature after the first, the DC increases by 5. When you finish a short or long rest, the DC resets to 10.

[#dreadnought-feature-persistent-rage]
== Persistent Rage
Beginning at 15th level, your rage is so fierce that it ends early only if you fall unconscious or if you choose to end it.

[#dreadnought-feature-indomitable-might]
== Indomitable Might
Beginning at 18th level, if your total for a Strength check is less than your Strength score, you can use that score in place of the total.

[#dreadnought-feature-primal-champion]
== Primal Champion
At 20th level, you embody the power of the wilds. Your Strength and Constitution scores increase by 4. Your maximum for those scores is now 24.

[#dreadnought-subclasses]
== {class-name-barbarian} Paths

[#dreadnought-subclasse-berserker]
=== {subclass-name-barbarian-berserker}
include::Paths/Path_of_the_Berserker.adoc[leveloffset=+2, tag=subclass]

[#dreadnought-subclasse-dragon]
=== {subclass-name-barbarian-dragon}
include::Paths/Path_of_the_Dragon.adoc[leveloffset=+2, tag=subclass]

// end::class[]