= Dwarf
:doctype: book
:icons: font
:revdate: May 1, 2025
:stem:
:stylesdir: ../../../css
:toc: left
// Custom attributes
ifndef::env-github[]
include::../../../attributes.adoc[]
endif::[]

// tag::ancestry[]

Sturdy and resilient, dwarves are known for their compact build with strong frames and broad features. Their intricate beards and braids often represent cultural pride. Dwarves have a reputation for craftsmanship and have a deep connection to the earth, often favoring mountainous or underground regions.

== Dwarf Traits
Your dwarf character has an assortment of inborn abilities, part and parcel of dwarven nature.

Age.:: Dwarves mature at the same rate as humans, but they’re considered young until they reach the age of 50. On average, they live about 350 years.

Size.:: Dwarves stand between 4 and 5 feet tall and average about 150 pounds. Your size is Medium.

Speed.:: Your base walking speed is 25 feet. Your speed is not reduced by wearing heavy armor.

Darkvision.:: Accustomed to life underground, you have superior vision in dark and dim conditions. You can see in dim light within 60 feet of you as if it were bright light, and in darkness as if it were dim light. You can’t discern color in darkness, only shades of gray.

Dwarven Resilience.:: You have advantage on saving throws against poison, and you have resistance against poison damage.

// end::ancestry[]